# Generated by Django 3.1.5 on 2021-02-25 05:56

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0023_auto_20201110_0834'),
        ('order', '0097_auto_20210107_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptPayPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promptpay_id', models.CharField(max_length=13)),
                ('qr_code', models.CharField(max_length=1000)),
                ('amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promptpay_payments', to='order.order')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promptpay_payments', to='payment.payment')),
            ],
        ),
    ]
