# Generated by Django 3.1.5 on 2021-03-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_auto_20210208_1820'),
        ('account', '0048_auto_20210308_1135'),
    ]

    operations = [
    ]
