# Generated by Django 3.1.5 on 2021-03-03 11:41

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0023_auto_20201110_0834'),
        ('order', '0097_auto_20210107_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptPayPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('amount_net', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('amount_fee', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('currency', models.CharField(max_length=5)),
                ('charge_id', models.CharField(max_length=200)),
                ('source_id', models.CharField(max_length=200)),
                ('qr_code_url', models.TextField(max_length=1000)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='omise_promptpay_payments', to='order.order')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='omise_promptpay_payments', to='payment.payment')),
            ],
        ),
    ]
