# Generated by Django 3.1.5 on 2021-03-06 17:07

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omise_payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=500)),
                ('key', models.CharField(max_length=200)),
                ('request_data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('request_header_data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('event_timestamp', models.DateTimeField()),
                ('received_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
